version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    links:
      - "db:database"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 25
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
